/**
 * Notion Integration Adapter for Delentia OS
 *
 * Connects Notion workspace operations to the Delentia OS Gateway via JITNA v3.
 * Supports page summarization, database queries, and auto-creation of
 * Notion pages from AI-generated intent outputs.
 *
 * Required ENV:
 *   NOTION_API_KEY         — Notion integration secret
 *   NOTION_DATABASE_ID     — Target database for auto-created entries
 *   DELENTIA_GATEWAY       — e.g. http://localhost:8000
 *   DELENTIA_API_KEY       — Bearer token for /v1/* endpoints
 */

import { executeIntent } from "@delentia/rct-edge";

// ── Types ─────────────────────────────────────────────────────────────────────

interface NotionPage {
  id: string;
  url: string;
  properties: Record<string, NotionProperty>;
  parent: { database_id?: string; page_id?: string; type: string };
}

interface NotionProperty {
  type: string;
  title?: Array<{ plain_text: string }>;
  rich_text?: Array<{ plain_text: string }>;
  select?: { name: string };
  date?: { start: string };
}

interface NotionBlock {
  type: string;
  paragraph?: { rich_text: Array<{ type: string; text: { content: string } }> };
}

// ── Notion API Client ─────────────────────────────────────────────────────────

const NOTION_VERSION = "2022-06-28";

async function notionRequest<T>(
  path: string,
  method: "GET" | "POST" | "PATCH",
  apiKey: string,
  body?: unknown
): Promise<T> {
  const res = await fetch(`https://api.notion.com/v1${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Notion-Version": NOTION_VERSION,
      "Content-Type": "application/json",
    },
    ...(body ? { body: JSON.stringify(body) } : {}),
  });
  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Notion API error ${res.status}: ${err}`);
  }
  return res.json() as Promise<T>;
}

// ── Page Text Extraction ──────────────────────────────────────────────────────

async function extractPageText(pageId: string, apiKey: string): Promise<string> {
  interface BlockList { results: NotionBlock[] }
  const blocks = await notionRequest<BlockList>(`/blocks/${pageId}/children`, "GET", apiKey);
  return blocks.results
    .filter((b) => b.paragraph)
    .map((b) =>
      b.paragraph!.rich_text.map((t) => t.text?.content ?? "").join("")
    )
    .join("\n")
    .slice(0, 8000); // Limit context size
}

// ── Create Notion Page from Intent Result ─────────────────────────────────────

async function createNotionPage(
  databaseId: string,
  title: string,
  content: string,
  apiKey: string
): Promise<NotionPage> {
  return notionRequest<NotionPage>("/pages", "POST", apiKey, {
    parent: { database_id: databaseId },
    properties: {
      Name: {
        title: [{ type: "text", text: { content: title.slice(0, 255) } }],
      },
      Source: {
        select: { name: "Delentia OS" },
      },
      "Created At": {
        date: { start: new Date().toISOString() },
      },
    },
    children: [
      {
        object: "block",
        type: "callout",
        callout: {
          rich_text: [
            {
              type: "text",
              text: { content: "🤖 Generated by Delentia OS — JITNA v3 · FDIA scored" },
            },
          ],
          icon: { type: "emoji", emoji: "⚡" },
          color: "blue_background",
        },
      },
      {
        object: "block",
        type: "paragraph",
        paragraph: {
          rich_text: [{ type: "text", text: { content: content.slice(0, 2000) } }],
        },
      },
    ],
  });
}

// ── Main: Summarize Notion Page ───────────────────────────────────────────────

export async function summarizeNotionPage(
  pageId: string,
  notionApiKey: string,
  gateway: string,
  apiKey: string
): Promise<string> {
  const pageText = await extractPageText(pageId, notionApiKey);
  if (!pageText.trim()) return "Page has no readable text content.";

  const result = await executeIntent({
    intent: `สรุปเนื้อหาจาก Notion page นี้โดยละเอียด: ${pageText}`,
    gateway,
    apiKey,
    metadata: { channel: "notion", page_id: pageId, operation: "summarize" },
  });

  return typeof result === "string"
    ? result
    : result?.response ?? result?.output ?? JSON.stringify(result);
}

// ── Main: Execute Intent and Save to Notion ───────────────────────────────────

export async function executeAndSaveToNotion(
  intentText: string,
  saveTitle: string,
  databaseId: string,
  notionApiKey: string,
  gateway: string,
  apiKey: string
): Promise<{ result: string; notionUrl: string }> {
  const result = await executeIntent({
    intent: intentText,
    gateway,
    apiKey,
    metadata: { channel: "notion", operation: "execute_and_save" },
  });

  const resultText =
    typeof result === "string"
      ? result
      : result?.response ?? result?.output ?? JSON.stringify(result);

  const page = await createNotionPage(databaseId, saveTitle, resultText, notionApiKey);

  return { result: resultText, notionUrl: page.url };
}
